server:
  port: 8090
spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      routes:
      - id: user-service
        uri: lb://user-service
        predicates:
          - Path=/api/user/**
        filters:
          - StripPrefix=2
      - id: account-service
        uri: lb://account-service
        predicates:
          - Path=/api/account/**
        filters:
          - StripPrefix=2
      - id: transaction-service
        uri: lb://transaction-service
        predicates:
          - Path=/api/transaction/**
        filters:
          - StripPrefix=2
      - id: ms-publisher
        uri: lb://ms-publisher
        predicates:
          - Path=/api/publisher/**
        filters:
          - StripPrefix=2
      - id: ms-consumer
        uri: lb://ms-consumer
        predicates:
          - Path=/api/consumer/**
        filters:
          - StripPrefix=2
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka